### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by gabotaco** [Gabolicious/AlfredBot#45]
/root/AlfredBot/slash.js:260
        } = interaction.member.user
                               ^

TypeError: Cannot read properties of undefined (reading 'user')
    at WebSocketManager.<anonymous> (/root/AlfredBot/slash.js:260:32)
    at WebSocketManager.emit (node:events:527:28)
    at WebSocketShard.onMessage (/root/AlfredBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:296:56)
    at WebSocket.onMessage (/root/AlfredBot/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/root/AlfredBot/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/root/AlfredBot/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/root/AlfredBot/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/root/AlfredBot/node_modules/ws/lib/receiver.js:143:22)

Node.js v17.9.1

**Comment by gabotaco** [comment]
https://github.com/rhit-corridg/AlfredBot/issues/51
