### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'roles')

### ISSUE THREAD

**Issue by gabotaco** [Gabolicious/AlfredBot#47]
/root/AlfredBot/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read properties of undefined (reading 'roles')
    **at Query.<anonymous> (/root/AlfredBot/functions.js:347:89)**
    at Query.<anonymous> (/root/AlfredBot/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/root/AlfredBot/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/root/AlfredBot/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/AlfredBot/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/AlfredBot/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/AlfredBot/node_modules/mysql/lib/protocol/Protocol.js:38:16)

**Comment by gabotaco** [comment]
https://github.com/rhit-corridg/AlfredBot/issues/51
