### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by gabotaco** [Gabolicious/AlfredBot#48]
/root/AlfredBot/Bothcommands/roles.js:37
            person.id == args.author_id &&
                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at /root/AlfredBot/Bothcommands/roles.js:37:11
    at new Promise (<anonymous>)
    at Object.module.exports.run (/root/AlfredBot/Bothcommands/roles.js:20:9)
    at Query.<anonymous> (/root/AlfredBot/Bothcommands/fire.js:32:41)
    at Query.<anonymous> (/root/AlfredBot/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/root/AlfredBot/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/root/AlfredBot/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/root/AlfredBot/node_modules/mysql/lib/protocol/Protocol.js:291:23)

Node.js v17.9.1

**Comment by TheGamerzs** [comment]
This error occurs when managers do /roles of a member not in that server where executed, as the member isn't in the guilds member cache.

That is probably why it's disabled in Alfred API.

Can be resolved by either:
If not found check the other server
Update roles in both companies servers

**Comment by gabotaco** [comment]
https://github.com/rhit-corridg/AlfredBot/issues/51
